Store/Controllers/ManageUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Store.Data;
using Store.Helpers;
using Store.Models;

namespace Store.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ManageUsersController : Controller
    {
        // todo: make the methods async -> use _userManager
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ManageUsersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            // todo: find a way to get this data in single query
            var usersList = await _context.Users.ToListAsync();
            var adminRoleId = await GetAdminRoleIdAsync();
            var usersViewList = new List<UserViewModel>();

            foreach (var user in usersList)
            {
                var userView = await CreateUserViewModelAsync(user, adminRoleId);
                usersViewList.Add(userView);
            }//for

            return View(usersViewList);
        }// Index()

        public async Task<IActionResult> Edit(string username)
        {
            if (string.IsNullOrEmpty(username))
            {
                return NotFound();
            }// if

            var adminRoleId = await GetAdminRoleIdAsync();
            var user = await _context.Users.SingleOrDefaultAsync(u => u.UserName == username);
            var userView = await CreateUserViewModelAsync(user, adminRoleId);

            return View(userView);
        }// Edit

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserViewModel userView)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(userView.Username);

                if (user == null)
                    return NotFound();

                var isInAdminRole = await _userManager.IsInRoleAsync(user, UserRoles.Admin);

                if (!userView.IsAdmin && isInAdminRole)
                    await _userManager.RemoveFromRoleAsync(user, UserRoles.Admin);
                else if(userView.IsAdmin && !isInAdminRole)
                    await _userManager.AddToRoleAsync(user, UserRoles.Admin);

                return RedirectToAction(nameof(Index));
            }//if

            return View(userView);
        }

        protected async Task<string> GetAdminRoleIdAsync()
        {
            var adminRole = await _context.Roles.SingleOrDefaultAsync(r => r.Name == UserRoles.Admin);
            return adminRole.Id;
        }

        protected async Task<UserViewModel> CreateUserViewModelAsync(IdentityUser user, string adminRoleId)
        {
            var userRole = await _context.UserRoles.SingleOrDefaultAsync(r => r.UserId == user.Id && r.RoleId == adminRoleId);

            var userView = new UserViewModel
            {
                Username = user.UserName,
                IsAdmin = userRole != null
            };

            return userView;
        }
    }
}

Store/Controllers/OrdersHistoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Store.Data;
using Store.Models;
using System.Linq;
using System.Threading.Tasks;

namespace Store.Controllers
{
    [Authorize]
    public class OrdersHistoryController : Controller
    {
        protected readonly ApplicationDbContext _context;
        protected readonly UserManager<ApplicationUser> _userManager;

        public OrdersHistoryController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var orders = _context.Orders.Where(o => o.UserId == currentUser.Id);

            return View(await orders.ToListAsync());
        }

        public async Task<IActionResult> Details(int id)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var order = await _context.Orders
                .Include(o => o.OrderLines)
                    .ThenInclude(ol => ol.Product)
                .SingleOrDefaultAsync(o => o.Id == id && o.UserId == currentUser.Id);
            if (order == null)
                return BadRequest();

            return View(order);
        }
    }
}

Store/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Store.Data;
using Store.Helpers;
using Store.Models;

namespace Store.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Products
        [AllowAnonymous]
        public async Task<IActionResult> Index(string search)
        {
            var products = from p in _context.Product
                           select p;

            if(!string.IsNullOrEmpty(search))
            {
                products = products.Where(p => p.Name.Contains(search));
            }

            products = products.Include(c => c.Category);

            return View(await products.ToListAsync());
        }

        // GET: Products/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.Include(c => c.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            var productCategories = _context.ProductCategory.ToList();

            var productViewModel = new EditProductViewModel
            {
                ProductCategories = productCategories
            };

            return View(productViewModel);
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EditProductViewModel editProductViewModel)
        {
            var editProduct = new EditProductViewModel
            {
                CategoryId = editProductViewModel.CategoryId,
                Description = editProductViewModel.Description,
                Image = editProductViewModel.Image,
                ImageFile = editProductViewModel.ImageFile,
                Name = editProductViewModel.Name,
                Price = editProductViewModel.Price,
                Rating = editProductViewModel.Rating
            };

            if (ModelState.IsValid)
            {
                var productCategory = _context.ProductCategory.SingleOrDefault(c => c.Id == editProduct.CategoryId);
                if (productCategory != null)
                {
                    var product = editProduct.ToDomainModel();

                    _context.Add(product);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }

            editProduct.ProductCategories = await _context.ProductCategory.ToListAsync();
            return View(editProduct);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            var editProductViewModel = new EditProductViewModel(product, _context);
            return View(editProductViewModel);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditProductViewModel editProductViewModel)
        {
            // TODO: image validation to prevent various attacks, see Create method
            if (id != editProductViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var product = editProductViewModel.ToDomainModel();

                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(editProductViewModel);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.Include(c => c.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Product.FindAsync(id);
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Product.Any(e => e.Id == id);
        }
    }
}

Store/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Store.Data;
using Store.Helpers;
using Store.Models;

namespace Store.Controllers
{
    public class ShoppingCartController : Controller
    {
        private const string sessionObjectKey = "ProductsInCart";
        private readonly ApplicationDbContext _context;

        public ShoppingCartController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Add(int productid)
        {
            var viewModel = await GetProductViewModelAsync(productid);
            if (viewModel == null)
                return NotFound();

            return View(viewModel);
        }

        public IActionResult AddConfirmed(ShoppingCartProductViewModel addedProduct)
        {
            if (addedProduct.Product == null || addedProduct.Product.Id < 1)
            {
                return BadRequest(); // todo: maybe redirect is better?
            }// if

            var productInCart = new ProductInCartSessionModel
            {
                ProductId = addedProduct.Product.Id,
                Quantity = addedProduct.Quantity
            };

            return View(productInCart);
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> List(ShoppingCartEncodedData shoppingCartData)
        {
            return View(await shoppingCartData.GetShoppingCartItemsAsync(_context));
        }

        public async Task<IActionResult> RemoveItem(int productId, int quantity)
        {
            var viewModel = await GetProductViewModelAsync(productId);
            if (viewModel == null)
                return NotFound();

            viewModel.Quantity = quantity; // todo: is that ok?

            return View(viewModel);
        }

        protected async Task<ShoppingCartProductViewModel> GetProductViewModelAsync(int productId)
        {
            var product = await _context.Product.FirstOrDefaultAsync(p => p.Id == productId);

            if (product == null)
                return null;

            var viewModel = new ShoppingCartProductViewModel
            {
                Product = product
            };

            return viewModel;
        }
        /*
         * Old code - not used anymore
         * Store shopping cart with session in ASP.NET
        public IActionResult AddConfirmed(ShoppingCartProductViewModel addProduct)
        {
            if (addProduct.Product == null || addProduct.Product.Id < 1)
            {
                return BadRequest();
            }// if

            var productInCart = new ProductInCartSessionModel
            {
                ProductId = addProduct.Product.Id,
                Quantity = addProduct.Quantity
            };

            var productsInCartList = HttpContext.Session.GetObjectFromJson<ProductsInCartListSessionModel>(sessionObjectKey);
            if(productsInCartList == null)
                productsInCartList = new ProductsInCartListSessionModel();

            productsInCartList.Products.Add(productInCart);

            HttpContext.Session.SetObjectAsJson(sessionObjectKey, productsInCartList);
            
            return Content("Added: " + addProduct.Product.Id + " Quantity: " + addProduct.Quantity);
        }//AddConfirmed()

        public IActionResult TestSession()
        {
            var productsInCartList = HttpContext.Session.GetObjectFromJson<ProductsInCartListSessionModel>(sessionObjectKey);

            if (productsInCartList == null)
                return NotFound();

            string contentString = string.Empty;

            foreach(var productInCart in productsInCartList.Products)
            {
                contentString += "ProductId: " + productInCart.ProductId + " Quantity: " + productInCart.Quantity + "\n";
            }

            return Content(contentString);
        }//TestSession()
        */
    }
}

Store/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Store</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Products" asp-action="Index">Store</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        
                        @if (User.IsInRole(Store.Helpers.UserRoles.Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ProductCategories" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ManageUsers" asp-action="Index">Users</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCart" asp-action="Index">Shopping Cart</a>
                        </li>

                        @if(User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="OrdersHistory" asp-action="Index">Orders history</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Store - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
        @*todo: add jQuery validation plugin here*@
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/ShoppingCart.js" asp-append-version="true"></script>
    <script src="~/js/ShoppingCartFormHelper.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Store/Views/Shared/_productsStringForm.cshtml
@model ShoppingCartEncodedData

<form id="products-string-form" asp-controller="ShoppingCart" asp-action="List">
    <input asp-for="productsString" class="form-control" type="hidden" />
</form>